### ISSUE TITLE
config.py 

### ISSUE THREAD

**Issue by akurach** [ruckus-dj/CWMTBot#2]
на 3 питоне: 
```
/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/sundelor/git/CWMTBot/Client.py
Traceback (most recent call last):
  File "/Users/sundelor/git/CWMTBot/Client.py", line 5, in <module>
    import config
  File "/Users/sundelor/Library/Python/3.6/lib/python/site-packages/config.py", line 733
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Process finished with exit code 1
```

**Comment by ruckus-dj** [comment]
Файл config.py нужно создать, скопировав demo_config.py и заполнив своими данными. Чуть позже напишу описание по установке и настройке.

**Comment by akurach** [comment]
да, уже понял. 
Если этого не сделать, он пытается модуль подгрузить))
